(in-package :qt)
(named-readtables:in-readtable :qt)

;; generate-image-array used to embed images into lisp code in an unsigned-byte array
(defun generate-image-array (filename &optional (stream *standard-output*) name)
  (with-open-file (f filename :direction :input :element-type '(unsigned-byte 8))
    (let ((len (file-length f)))
      (let ((image (make-array len :element-type '(unsigned-byte 8))))
        (read-sequence image f)
        (format stream "(defvar ~A~%" (or name "NAME"))
        (format stream "   #(" )
        (dotimes (i len)
          (when (and (not (zerop i)) (zerop (mod i 16)))
            (format stream "~%     "))
          (format stream "#x~2,'0X " (aref image i)))
        (format stream "))~%~%")
        nil))))

(defun pixmap-svg (svg-image)
  (with-objects ((svg-data (#_new QByteArray svg-image)))
    (with-objects ((svg-buf (#_new QBuffer svg-data)))
      (unwind-protect
           (progn
             (#_open svg-buf (#_QIODevice::ReadOnly))
             (with-objects ((image-reader (#_new QImageReader svg-buf "SVG")))
               (let ((image (#_QPixmap::fromImageReader image-reader)))
                 (#_close svg-buf)
                 image)))))))

;; pixmap return the QPixmap class, is an off-screen image representation that can be used as a paint device
(defun pixmap (image format)
  (if (string-equal format "SVG")
      (pixmap-svg image)
      (let ((len (length image)))
        (let ((dataptr (cffi:foreign-alloc :uint8 :count len)))
          (dotimes (i len)
            (setf (cffi:mem-aref dataptr :uint8 i) (aref image i)))
          (let ((res (#_QPixmap::fromImage (#_QImage::fromData dataptr len format))))
            (cffi:foreign-free dataptr)
            res)))))
